Player.destroy_all
Territory.destroy_all

Player.create(name: "Phil")
Player.create(name: "Shannon")

Territory.create(player_id: 2, power: 5)
Territory.create(player_id: 1, power: 5)
Territory.create(player_id: 1, power: 5)
Territory.create(player_id: 2, power: 5)
Territory.create(player_id: 1, power: 5)
Territory.create(player_id: 2, power: 5)
Territory.create(player_id: 2, power: 5)
Territory.create(player_id: 1, power: 5)
Territory.create(player_id: 1, power: 5)
Territory.create(player_id: 2, power: 5)
Territory.create(player_id: 1, power: 5)
Territory.create(player_id: 2, power: 5)

Neighbor.create(base_id: 1, neighbor_id: 2)
Neighbor.create(base_id: 1, neighbor_id: 5)
Neighbor.create(base_id: 2, neighbor_id: 1)
Neighbor.create(base_id: 2, neighbor_id: 3)
Neighbor.create(base_id: 2, neighbor_id: 6)
Neighbor.create(base_id: 3, neighbor_id: 2)
Neighbor.create(base_id: 3, neighbor_id: 4)
Neighbor.create(base_id: 3, neighbor_id: 7)
Neighbor.create(base_id: 4, neighbor_id: 3)
Neighbor.create(base_id: 4, neighbor_id: 8)
Neighbor.create(base_id: 5, neighbor_id: 1)
Neighbor.create(base_id: 5, neighbor_id: 6)
Neighbor.create(base_id: 5, neighbor_id: 9)
Neighbor.create(base_id: 6, neighbor_id: 2)
Neighbor.create(base_id: 6, neighbor_id: 5)
Neighbor.create(base_id: 6, neighbor_id: 7)
Neighbor.create(base_id: 6, neighbor_id: 10)
Neighbor.create(base_id: 7, neighbor_id: 3)
Neighbor.create(base_id: 7, neighbor_id: 6)
Neighbor.create(base_id: 7, neighbor_id: 8)
Neighbor.create(base_id: 7, neighbor_id: 11)
Neighbor.create(base_id: 8, neighbor_id: 4)
Neighbor.create(base_id: 8, neighbor_id: 7)
Neighbor.create(base_id: 8, neighbor_id: 12)
Neighbor.create(base_id: 9, neighbor_id: 5)
Neighbor.create(base_id: 9, neighbor_id: 10)
Neighbor.create(base_id: 10, neighbor_id: 6)
Neighbor.create(base_id: 10, neighbor_id: 9)
Neighbor.create(base_id: 10, neighbor_id: 11)
Neighbor.create(base_id: 11, neighbor_id: 7)
Neighbor.create(base_id: 11, neighbor_id: 10)
Neighbor.create(base_id: 11, neighbor_id: 12)
Neighbor.create(base_id: 12, neighbor_id: 8)
Neighbor.create(base_id: 12, neighbor_id: 11)
