Player.destroy_all
Territory.destroy_all

Player.create(name: "Phil")
Player.create(name: "Shannon")

t1 = Territory.create(name: "People's Republic of Chine", player_id: 2, power: 5)
t2 = Territory.create(name: "Jamestown", player_id: 1, power: 5)
t3 = Territory.create(name: "DCJonesville", player_id: 2, power: 5)
t4 = Territory.create(name: "nePAUL", player_id: 1, power: 5)
t5 = Territory.create(name: "USSRtem", player_id: 2, power: 5)
t6 = Territory.create(name: "Philtopia", player_id: 1, power: 5)
t7 = Territory.create(name: "Haiwan", player_id: 1, power: 5)
t8 = Territory.create(name: "Heloisiana", player_id: 1, power: 5)
t9 = Territory.create(name: "Andrea Empire", player_id: 1, power: 5)
t10 = Territory.create(name: "AntManland", player_id: 1, power: 5)
t11 = Territory.create(name: "Mattland", player_id: 1, power: 5)
t12 = Territory.create(name: "Ryanland", player_id: 1, power: 5)
t13 = Territory.create(name: "MoShinik", player_id: 1, power: 5)
t14 = Territory.create(name: "Melville", player_id: 1, power: 5)
t15 = Territory.create(name: "Jake", player_id: 1, power: 5)
t16 = Territory.create(name: "Annada", player_id: 1, power: 5)
t17 = Territory.create(name: "Benland", player_id: 1, power: 5)
t18 = Territory.create(name: "Bennsylvania", player_id: 1, power: 5)
t19 = Territory.create(name: "Bossnia", player_id: 1, power: 5)
t20 = Territory.create(name: "Servantes", player_id: 1, power: 5)
t21 = Territory.create(name: "UzbekiShan", player_id: 1, power: 5)
t22 = Territory.create(name: "The Kysland", player_id: 1, power: 5)

Neighbor.create(base_id: 1, neighbor_id: 2)
Neighbor.create(base_id: 1, neighbor_id: 3)
Neighbor.create(base_id: 2, neighbor_id: 1)
Neighbor.create(base_id: 2, neighbor_id: 3)
Neighbor.create(base_id: 3, neighbor_id: 1)
Neighbor.create(base_id: 3, neighbor_id: 2)
Neighbor.create(base_id: 3, neighbor_id: 4)
Neighbor.create(base_id: 3, neighbor_id: 19)
Neighbor.create(base_id: 4, neighbor_id: 3)
Neighbor.create(base_id: 4, neighbor_id: 18)
Neighbor.create(base_id: 4, neighbor_id: 5)
Neighbor.create(base_id: 5, neighbor_id: 4)
Neighbor.create(base_id: 5, neighbor_id: 18)
Neighbor.create(base_id: 5, neighbor_id: 6)
Neighbor.create(base_id: 5, neighbor_id: 7)
Neighbor.create(base_id: 6, neighbor_id: 5)
Neighbor.create(base_id: 6, neighbor_id: 7)
Neighbor.create(base_id: 7, neighbor_id: 5)
Neighbor.create(base_id: 7, neighbor_id: 6)
Neighbor.create(base_id: 7, neighbor_id: 8)
Neighbor.create(base_id: 8, neighbor_id: 7)
Neighbor.create(base_id: 8, neighbor_id: 9)
Neighbor.create(base_id: 8, neighbor_id: 10)
Neighbor.create(base_id: 9, neighbor_id: 8)
Neighbor.create(base_id: 9, neighbor_id: 10)
Neighbor.create(base_id: 10, neighbor_id: 8)
Neighbor.create(base_id: 10, neighbor_id: 9)
Neighbor.create(base_id: 10, neighbor_id: 12)
Neighbor.create(base_id: 10, neighbor_id: 13)
Neighbor.create(base_id: 10, neighbor_id: 14)
Neighbor.create(base_id: 11, neighbor_id: 12)
Neighbor.create(base_id: 11, neighbor_id: 13)
Neighbor.create(base_id: 12, neighbor_id: 11)
Neighbor.create(base_id: 12, neighbor_id: 10)
Neighbor.create(base_id: 13, neighbor_id: 10)
Neighbor.create(base_id: 13, neighbor_id: 11)
Neighbor.create(base_id: 13, neighbor_id: 14)
Neighbor.create(base_id: 13, neighbor_id: 15)
Neighbor.create(base_id: 13, neighbor_id: 20)
Neighbor.create(base_id: 14, neighbor_id: 10)
Neighbor.create(base_id: 14, neighbor_id: 13)
Neighbor.create(base_id: 14, neighbor_id: 15)
Neighbor.create(base_id: 14, neighbor_id: 16)
Neighbor.create(base_id: 15, neighbor_id: 13)
Neighbor.create(base_id: 15, neighbor_id: 14)
Neighbor.create(base_id: 15, neighbor_id: 16)
Neighbor.create(base_id: 15, neighbor_id: 20)
Neighbor.create(base_id: 16, neighbor_id: 14)
Neighbor.create(base_id: 16, neighbor_id: 15)
Neighbor.create(base_id: 16, neighbor_id: 17)
Neighbor.create(base_id: 16, neighbor_id: 18)
Neighbor.create(base_id: 17, neighbor_id: 16)
Neighbor.create(base_id: 17, neighbor_id: 18)
Neighbor.create(base_id: 17, neighbor_id: 19)
Neighbor.create(base_id: 18, neighbor_id: 16)
Neighbor.create(base_id: 18, neighbor_id: 17)
Neighbor.create(base_id: 18, neighbor_id: 4)
Neighbor.create(base_id: 18, neighbor_id: 5)
Neighbor.create(base_id: 19, neighbor_id: 3)
Neighbor.create(base_id: 19, neighbor_id: 17)
Neighbor.create(base_id: 19, neighbor_id: 20)
Neighbor.create(base_id: 19, neighbor_id: 21)
Neighbor.create(base_id: 20, neighbor_id: 13)
Neighbor.create(base_id: 20, neighbor_id: 15)
Neighbor.create(base_id: 20, neighbor_id: 19)
Neighbor.create(base_id: 20, neighbor_id: 21)
Neighbor.create(base_id: 21, neighbor_id: 19)
Neighbor.create(base_id: 21, neighbor_id: 20)
Neighbor.create(base_id: 21, neighbor_id: 22)
Neighbor.create(base_id: 22, neighbor_id: 21)
